// Generated by CoffeeScript 1.10.0
(function() {
  var add, greet, i, len, student, students;

  greet = function() {
    return console.log("Hello how are you");
  };

  add = function(a, b) {
    var c;
    c = a + b;
    return console.log("Sum of the two numbers is: " + c);
  };

  greet();

  add(10, 20);

  students = ["Rahman", "Ramu", "Ravi", "Robert"];

  for (i = 0, len = students.length; i < len; i++) {
    student = students[i];
    console.log(student);
  }

}).call(this);
